### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by agjaeger** [knightcrawler25/GLSL-PathTracer#12]
Hi, I was looking through your scenes and they reference some missing files, was this done on purpose because they are closed source or just an oversight?

The scenes are beautiful and I would love to test them in my raytracer.

**Comment by knightcrawler25** [comment]
I probably forgot to include them but for now you can find some of the assets in my other repo here: https://github.com/knightcrawler25/Optix-PathTracer/blob/master/src/data/data.rar

Some other ones like the dragon model and staircase scene from here: https://benedikt-bitterli.me/resources/

The Rank 3 Police scene is from SketchFab: https://sketchfab.com/models/d7698f6a7acf49c68ff0a50c5a1b1d52

**Comment by knightcrawler25** [comment]
The readme now has a link to almost all the assets from the screenshots. Closing the issue.
