### ISSUE TITLE
Scene loading failed on window

### ISSUE THREAD

**Issue by frame-r** [knightcrawler25/GLSL-PathTracer#19]
I'm trying load scene CoffeeCart.scene. Paths like ./assets/bathroom/floor.obj can't be loaded on window VS 2019. Assert genarated

**Comment by knightcrawler25** [comment]
Right now only .scene files for ajax/boy/cornell will work since only these have the corresponding .obj files available in the repo. The project is mostly a WIP and so I didn't add all the files. If needed I can share them through a Google drive link :)

**Comment by frame-r** [comment]
It would be great;) Because I wanted to test the render on other scenes

**Comment by knightcrawler25** [comment]
I've uploaded some of the scenes here: https://drive.google.com/file/d/1UFMMoVb5uB7WIvCeHOfQ2dCQSxNMXluB/view

You can load these from the command line:
pathtracer.exe -s assets/diningroom.scene

**Comment by frame-r** [comment]
Thx!

**Comment by knightcrawler25** [comment]
Closing since the link has also been added to the readme and will be updated with any new scenes/assets in the future.
