### ISSUE TITLE
Planned things on my fork

### ISSUE THREAD

**Issue by CedricGuillemet** [knightcrawler25/GLSL-PathTracer#2]
Here is a small list of things I'd like to do/like to see in the coming weeks/months (no particular order):
~~provide API for rendering progress feedback~~
~~dearimgui UI : load scene, change rendering mode, dump infos~~

~~use cmake and move files (3rd party libs are not properly placed)~~
- provide memory allocator
- use assimp instead of tinyobj loader. .obj loading is inefficient and corrupts github merge info (got 1.8M+line change in my PR)

**Comment by knightcrawler25** [comment]
Hey Cedric,

Thanks for contributing :) 
I didn't know how to set up cmake so dumped the visual studio solution in the project. Rearranging the 3rd party libs and a UI would be nice. 
Also, I couldn't understand the third and fourth points about the memory allocator and corruption with the merge info. Could you share some more info?

**Comment by CedricGuillemet** [comment]
by providing a memory allocator you get more control on allocation, memory budget,...
.obj is text and when you commit a 60Mb .obj file you get like 1million new lines in the github PR

**Comment by knightcrawler25** [comment]
Ah I see. I thought you meant the code to load obj was causing an issue.

**Comment by CedricGuillemet** [comment]
1 more done :)
