### ISSUE TITLE
Missing dll when running PathTracer.exe

### ISSUE THREAD

**Issue by oktomus** [knightcrawler25/GLSL-PathTracer#20]
First of all, thanks a lot for sharing a release ! 

I'm missing a Visual C++ Redistributable Package to run your executable. Maybe you could provide details somewhere on what needs to be installed before running your program ?

![image](https://user-images.githubusercontent.com/4656466/88888562-d4e7fc80-d23e-11ea-8c0f-d6c5d9bce205.png)

**Comment by knightcrawler25** [comment]
Can you try downloading and installing the Visual C++ redistributables (x64) from this [link](https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads). Let me know if it works

**Comment by oktomus** [comment]
It works ! Thanks a lot :) 

![image](https://user-images.githubusercontent.com/4656466/88910167-54d08f80-d25c-11ea-84d3-8f9acfec25da.png)
