### ISSUE TITLE
Better samples generation

### ISSUE THREAD

**Issue by oktomus** [knightcrawler25/GLSL-PathTracer#21]
We can see weird patterns in the samples.

![image](https://user-images.githubusercontent.com/4656466/88910212-6d40aa00-d25c-11ea-984f-99cf9371b77c.png)

Maybe it is related to the RNG ?

I had a similar issue that I fixed on my [toy renderer](https://github.com/oktomus/web-experiments#webgl-20-compute-random-number-generator) using another RNG. 

For reference:
- [RNG on shader toy ](https://www.shadertoy.com/view/tstXWS)

**Comment by knightcrawler25** [comment]
Could be, but I'm unable to see those repetitive patterns on my PC. What GPU are you on?

**Comment by oktomus** [comment]
RTX 2080.

Can you point me to the place where the samples are generated?

**Comment by knightcrawler25** [comment]
The rand() function is in src/shaders/common/globals.glsl
and the seed is set in src/shaders/tiled.glsl
