### ISSUE TITLE
openGL error when using progressive renderer with glassboy

### ISSUE THREAD

**Issue by CedricGuillemet** [knightcrawler25/GLSL-PathTracer#3]
I get an openGL error reported when trying to render glassboy with a progressive renderer
GL Debug (ERROR - HIGH) Error has been generated. GL error GL_INVALID_ENUM in TexStorage3D: (ID: 1669289888) Generic error 
this corresponds to https://github.com/knightcrawler25/GLSL-PathTracer/blob/master/PathTracer/src/Renderer.cpp#L83

**Comment by knightcrawler25** [comment]
The parameters to glTexStorage3D were not correct. Setting the 2nd parameter to 0 and third to GL_RGB8 works for me:

 glTexStorage3D(GL_TEXTURE_2D_ARRAY, 0, GL_RGB8, (int)(scene->texData.albedoTextureSize.x), (int)(scene->texData.albedoTextureSize.y), scene->texData.albedoTexCount);

This has to be changed for all 4 calls when loading albedo, metallic, roughness and normal textures. Let me know if this works

**Comment by knightcrawler25** [comment]
Let me know if that change worked

**Comment by knightcrawler25** [comment]
Closing this issue since its fixed now
