### ISSUE TITLE
How to make my own scene for rendering inside the engine?

### ISSUE THREAD

**Issue by odil24** [knightcrawler25/GLSL-PathTracer#33]
I'm Blender user and I'd like to export my scene from Blender as OBJ file and then would like to render inside the engine, but how to do this?

Thanks advance.

**Comment by Mentalarray** [comment]
you just look at the scene examples i.e cornell_box.scene its show you how to include .obj format mesh files and to set materials

**Comment by odil24** [comment]
Are you mean am I must to understand this lines from the .scene files?
[img]https://i.postimg.cc/wM66RswB/screenshot-182.png[/img]

**Comment by Mentalarray** [comment]
the link you posted is not working

**Comment by HackerDaGreat57** [comment]
How 'bout we just add a full-fledged editor to the whole thing? And rename it to something new.... like **PixelPro** or **Blender 3.0** or something.

**Comment by Tetsujinfr** [comment]
The way the materials are stored in the scene format is different from the .mtl format: is there already a piece of code to convert std mtl files into the .scene format or one has to code a conversion tool?
thanks

**Comment by Mentalarray** [comment]
The regular mtl format does not support PBR materials if your using blender you could build your own exporter on python to include PBR along these lines http://exocortex.com/blog/extending_wavefront_mtl_to_support_pbr

**Comment by Tetsujinfr** [comment]
I see thanks. So I conclude that the pbr world has no std format then and then this repo uses its own specific one. (I am not close to the cgi world/industry, bear with me)
I am not a blender user and although I know this is a great tool I do not want to make it a dependency or my workflow when using the glsl path tracer.
Thanks for the link, great suggestion. will try to DIY some formats conversion code.
