### ISSUE TITLE
Issue with large scale models

### ISSUE THREAD

**Issue by pbondd** [knightcrawler25/GLSL-PathTracer#35]
Hello,
I have a problem that seems to be related to the measure unit adopted. I would like to use obj models in scale 1.0 unit = 1mm.
![img_184](https://user-images.githubusercontent.com/81223042/112119108-5a009700-8bbd-11eb-9f57-32a3c2f7d923.jpg)
This is a screenshot of the teapot.scene where the object is scaled up to be 100 times bigger.
I previously tried a version of this path tracer in October 2020 and I didn't experienced this issue.

Thanks and congrats for your great job.

**Comment by knightcrawler25** [comment]
Hey! From the screenshot, it looks like a self intersection issue. With every bounce the ray position needs to be offset a tiny amount along the surface normal to avoid self intersections and at that scale, the offset amount might not be sufficient.

Can you try modifying the EPS variable at the following line to something like 0.1 and see if that fixes the issue?

https://github.com/knightcrawler25/GLSL-PathTracer/blob/ca8f08873a9fac0acfcfad551fae301ad2282ef2/src/shaders/common/globals.glsl#L28

**Comment by pbondd** [comment]
Yes, this solves the issue!
It may be possible to adjust this param accordingly to the main bounding box size, but in general I agree that this is scene dependent. 

Many thanks!
