### ISSUE TITLE
Fix to screenshots crashes

### ISSUE THREAD

**Issue by pbondd** [knightcrawler25/GLSL-PathTracer#44]
Hi,

I may have a fix for the screenshot crashes. 
The reason must be non POT textures, so i've just added:
`glPixelStorei(GL_PACK_ALIGNMENT, 1);`
before
https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/core/TiledRenderer.cpp#L411

**Comment by knightcrawler25** [comment]
This seems to have fixed the issue. Thanks a lot! :D
