### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by viskogurl** [knightcrawler25/GLSL-PathTracer#45]
I know the benefit of path tracing is that it enables dynamic, photorealistic lighting but would it (theoretically) be possible to bake the path traced lighting into a scene or asset?

Feel free to just close the issue if this is a stupid question; I'm new to graphics and such.

**Comment by knightcrawler25** [comment]
I'm not sure if your question was specifically around this project or just a general one, but it is possible to bake lighting info into textures using a process called lightmapping. Some slides on how it works: https://www.slideshare.net/unity3d/progressive-lightmapper-an-introduction-to-lightmapping-in-unity

**Comment by viskogurl** [comment]
The question was referring to your project but I now understand a little better how it works. I have a lot of static objects in my scene so I was just wondering if there was a way to bake the path traced lighting into them instead of having to re-render the scene each time a move a single object. I haven't seen any lightmapped scenes that compare with path traced solutions such as yours so that's why I asked :)

Thank you very much for the resource and the response!

**Comment by Zi7ar21** [comment]
If you move an object, the way light bounces off of it changes. You can only bake lighting for a static scene, and even then there is restrictions e.g. you can't have dielectric materials. I mean you could have 100% reflective objects and just ray-trace reflections... Either way, I don't think that's the scope of this project and I anticipate the maintainers won't implement it.

**Comment by knightcrawler25** [comment]
The problem that would come up if even a single object is moved is that the lightmap for the scene has to be recalculated as the lighting would've been baked into textures with the object's previous position. At most, only the camera can be moved after baking which doesn't offer a lot of advantages. For dynamic objects, light probes have to be used but all of these methods are more suited to real time rendering and would only add additional complexity the simple nature of this project.

**Comment by Zi7ar21** [comment]
Did we just respond at the same time? What are the odds!

**Comment by knightcrawler25** [comment]
@Zi7ar21 Haha I saw your response pop up a second before I clicked on the comment button.

**Comment by viskogurl** [comment]
Ahh, okay. I think Raymarching is probably better suited for what I'm trying to accomplish then so I'll take a look in that direction.

Thank you @knightcrawler25 and @Zi7ar21  both so much for the info!

**Comment by knightcrawler25** [comment]
No worries :) Glad to help. Feel free to re-open if you have any questions.
