### ISSUE TITLE
Check if inside Object

### ISSUE THREAD

**Issue by markusmoenig** [knightcrawler25/GLSL-PathTracer#46]
Hi, I am writing an SDF modeler and for the ray marching to be correct I need to know if the path tracer state is currently inside or outside an object.

Would that be somehow evident from the State struct ?

Thanks

**Comment by knightcrawler25** [comment]
You can probably get that information from the surface normal. If state.normal and state.fformal are on the same side then the ray has hit the surface from the outside, otherwise, the ray has hit the inner surface.

**Comment by markusmoenig** [comment]
Thanks, that makes sense. I just need to make sure to inverse the ray marching direction when inside as otherwise I would trace back.
