### ISSUE TITLE
Feature request: Improving OIDN using albedo and normal maps

### ISSUE THREAD

**Issue by er888kh** [knightcrawler25/GLSL-PathTracer#49]
Is it possible to get the normal and albedo values from the shader to OIDN? It will improve the image quality by a lot.

**Comment by knightcrawler25** [comment]
It could be possible, but with something like depth of field enabled, I think the aux buffers would also require several samples. [Documentation](https://github.com/OpenImageDenoise/oidn) suggests cleaning up the aux buffers if they are noisy. If that is the case, then having these buffers generated along with the final image might make more sense as that will tie everything together
