### ISSUE TITLE
Feature wanted

### ISSUE THREAD

**Issue by CedricGuillemet** [knightcrawler25/GLSL-PathTracer#5]
New feature request :)
I don't know if it fits your roadmap but I'd like to see displacement texture in the material. I'm working a lot with heightmap/displacement map and I'd like to plug the renderer over that. Thanks !

**Comment by knightcrawler25** [comment]
I'll try this ray marched method out this weekend and see how it goes:

https://developer.nvidia.com/gpugems/GPUGems2/gpugems2_chapter08.html

I looked up some references on vector displacement but it seems quite involved to get right:

https://blog.yiningkarlli.com/2017/05/subdivision-and-displacement.html

http://gpupro.blogspot.com/2015/03/gpu-pro-6-rendering-vector-displacement.html?m=1

Any suggestions?

**Comment by CedricGuillemet** [comment]
Maybe this one:
http://www.iquilezles.org/www/articles/terrainmarching/terrainmarching.htm

**Comment by knightcrawler25** [comment]
I'm a couple of years late lol but for anyone new reading this, closing the issue since pre-tessellation for displacement mapping will blow up tri counts and on the fly tessellation isn't really suited to be done in a pixel shader.
