### ISSUE TITLE
Is 2 *pi * pi -> 2 * two_pi typo or bug fixing?

### ISSUE THREAD

**Issue by tigrazone** [knightcrawler25/GLSL-PathTracer#58]
Hello.
Is 2.0 * PI * PI changing to 2.0 * TWO_PI are correct? Or it is error or typo?
Please explain this changing

**Comment by knightcrawler25** [comment]
Its a typo. I mistook it for PI + PI and changed it to TWO_PI. Thanks for letting me know :)
