### ISSUE TITLE
Why dot and specular parameter is removed?

### ISSUE THREAD

**Issue by tigrazone** [knightcrawler25/GLSL-PathTracer#59]
Hello.
Why in bsdfSampleRec.f * abs(dot(state.ffnormal, bsdfSampleRec.L)) / bsdfSampleRec.pdf; and same in other places in code
abs(dot(state.ffnormal, bsdfSampleRec.L))  is removed?
Why specular parameter is removed?

**Comment by knightcrawler25** [comment]
The N.L was just moved to the BSDF sample and eval functions

https://github.com/knightcrawler25/GLSL-PathTracer/blob/a937e046402b5acdbe0415b98c99dc54ff8a18cd/src/shaders/common/disney.glsl#L214

https://github.com/knightcrawler25/GLSL-PathTracer/blob/a937e046402b5acdbe0415b98c99dc54ff8a18cd/src/shaders/common/disney.glsl#L276

The specular parameter was removed as section 3.2 of the [2015 Disney BSDF notes](https://blog.selfshadow.com/publications/s2015-shading-course/burley/s2015_pbs_disney_bsdf_notes.pdf) mentions using ior so the ior parameter now controls the reflectivity (to be more in sync with the paper)

![GIF 29-Nov-21 5-15-37 PM](https://user-images.githubusercontent.com/11459803/143862482-839fab82-a685-459a-b7fe-d8b4aab56b9d.gif)

**Comment by tigrazone** [comment]
Thank you for explaination
