### ISSUE TITLE
scene file light format

### ISSUE THREAD

**Issue by vtushevskiy** [knightcrawler25/GLSL-PathTracer#63]
How do you define quad lights in .scene file? There is position, v1, v2 parameters.
Is 'position' a coordinates of the center of light? What are 'v1' and 'v2' vectors?
UPDATE
I think position, v1, v2 are just coordinates of the first three vertices of area light, right?

**Comment by knightcrawler25** [comment]
position, v1 and v2 are the 3 vertices that define a quad like so:

![image](https://user-images.githubusercontent.com/11459803/147865828-b9eefb8a-a1b9-45ba-a3fb-5674af809af1.png)

Internally, u and v are calculated as v1 - position and v2 - position and cross product of u and v determines the emission side or the normal of the light
