### ISSUE TITLE
Question: moving lights

### ISSUE THREAD

**Issue by ib00** [knightcrawler25/GLSL-PathTracer#70]
Is it possible to interactively move lights in a scene?

**Comment by knightcrawler25** [comment]
Unlike mesh instances, lights currently don't have have an associated transformation matrix so they cannot be translated/rotated/scaled interactively.

**Comment by ib00** [comment]
Thanks. Amazing work on the raytracer. Very impressive!

**Comment by knightcrawler25** [comment]
Thank you for the kind words :)
