### ISSUE TITLE
Improving Build intructions

### ISSUE THREAD

**Issue by LucienGab** [knightcrawler25/GLSL-PathTracer#71]
hey I'm kind of stupid and I keep on getting stuck on the part where you open the sln because there isn't one so if you could add screenshots to the build instructions that'd be great
![image](https://user-images.githubusercontent.com/73358079/179554473-1d0bade1-ceae-48ab-8ffc-0492073d0f1f.png)

**Comment by knightcrawler25** [comment]
Hey :)

The location you've selected in cmake to build the binaries should have a "PathTracer.sln" file in it.

![image](https://user-images.githubusercontent.com/11459803/179580585-69e204b1-df5c-487e-a40f-73303f645d78.png)

For the above example, this is how the folder structure would look like:
![image](https://user-images.githubusercontent.com/11459803/179581517-33e2c622-8a6a-480a-90cd-bf1c26de854d.png)

Under the build folder would be the .sln file. 
![image](https://user-images.githubusercontent.com/11459803/179581557-30e2e0c9-2281-423d-8e28-94d2fb8da79b.png)
