### ISSUE TITLE
Question on implementation of  Transmission and Reflection

### ISSUE THREAD

**Issue by Jack12xl** [knightcrawler25/GLSL-PathTracer#72]
I noticed on this line https://github.com/knightcrawler25/GLSL-PathTracer/blob/22b136c34a2369dd3f2e1f942e2d37b9594484dd/src/shaders/common/disney.glsl#L217
 You use un-sampled `L` to estimate the fresnel term. Wonder if this is valid😮?

**Comment by knightcrawler25** [comment]
Hey @Jack12xl

You're right. It's not valid to use L when that's what we're trying to find :D

Thanks for finding this. I'll update the code soon.

**Comment by knightcrawler25** [comment]
This should be fixed now (71b16a18645245c893280a8eda3cc438dc4ca330).
