### ISSUE TITLE
Fix quarter rendering window issue in MacOS

### ISSUE THREAD

**Issue by LeeTeng2001** [knightcrawler25/GLSL-PathTracer#73]
The actual resolution of window is different if you have retina display (like MacOS), thus we need to query from SDL once more after we have created the window to get the actual drawable size. Thus will fix the black range in the rendering window

```
    auto window_flags = (SDL_WindowFlags) (SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE |
                                                      SDL_WINDOW_ALLOW_HIGHDPI);
    loopdata.mWindow = SDL_CreateWindow("GLSL Raytracing", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                        renderOptions.windowResolution.x, renderOptions.windowResolution.y,
                                        window_flags);
    
    // Query actual drawable window size
    int w, h;
    SDL_GL_GetDrawableSize(loopdata.mWindow, &w, &h);
    renderOptions.windowResolution.x = w;
    renderOptions.windowResolution.y = h;
```

Before:
![Screenshot 2022-12-14 at 10 38 20 AM](https://user-images.githubusercontent.com/63984709/207491918-cacf29ae-71d4-4ecd-925f-4b3dfc363c89.jpg)

After:
![Screenshot 2022-12-14 at 10 38 43 AM](https://user-images.githubusercontent.com/63984709/207491941-46103a14-4899-4d00-9a39-c8d04080ad5f.jpg)

**Comment by LeeTeng2001** [comment]
Should be an easy fix

**Comment by knightcrawler25** [comment]
Thanks. I've added the code you've suggested. 

Also, out of curiosity, did you have to make other changes to get the code to run on a Mac?

**Comment by LeeTeng2001** [comment]
Yes I did, do you want me to make a pr branch for adding support for MacOS build?

**Comment by knightcrawler25** [comment]
That'll be helpful as I don't have a way to test the repo on macOS :)

**Comment by LeeTeng2001** [comment]
ok! I'll work on it after my exam (which will be around early jan)

**Comment by LeeTeng2001** [comment]
I'll open another issue
