### ISSUE TITLE
Reading materials for the shader pipeline in the code

### ISSUE THREAD

**Issue by LeeTeng2001** [knightcrawler25/GLSL-PathTracer#76]
I find it hard to understand everything that's going on in the shader folder, do you have any reference i can look up to?

**Comment by knightcrawler25** [comment]
I would recommend skimming through https://raytracing.github.io/ as it'll give you an overview of what goes into building a path tracer.

If you're already familiar with that book then PBRT https://www.pbr-book.org/3ed-2018/contents would be the best source as it covers everything that you would come across in the shaders folder. 

Although the code in this repo differs from PBRT, the core ideas behind it remain the same. Here are some of the topics you can go over:

1. Camera model
2. Ray triangle intersection
3. Bounding volume hierarchies (BVH)
4. Monte Carlo integration & sampling
5. Reflection, transmission & the microfacet BSDF
6. Lights (Area, Distant, Infinite Area)
7. Direct lighting and MIS
8. Basic volume rendering (Homogeneous volumes)
9. Phase functions (volumetric analog of a BSDF)

Also, if you have any questions, you can ask here :)
