### ISSUE TITLE
hello,Why is this error when I open and build the solution in vs after I do my project cmake? How Do We Fix This?

### ISSUE THREAD

**Issue by jlk1997** [knightcrawler25/GLSL-PathTracer#80]
![image](https://user-images.githubusercontent.com/56379549/211284334-8b08b01c-d2d2-4412-a7b0-67d82de61a18.png)
![image](https://user-images.githubusercontent.com/56379549/211284424-ca44f36a-c6e1-4749-bf9b-c689f669e744.png)

**Comment by knightcrawler25** [comment]
Can you send a screenshot of the linker command line:

![image](https://user-images.githubusercontent.com/11459803/211347509-253dbd2b-160c-47bf-8d88-0622b05b7c29.png)

Can you also try deleting the build folder and run these 3 commands one after the other and share the entire output?

```
mkdir build
cmake -G "Visual Studio 17 2022" -A x64 . -B build
cmake --build build --config Release

```

**Comment by jlk1997** [comment]
![image](https://user-images.githubusercontent.com/56379549/211451133-9a91d5c8-c9b4-43c6-b35a-f621e7f01a47.png)
thx a lot .I tried again, but it didn't work. Maybe it's a library conflict, but I'm not sure what I want to do. For now, maybe it's a library conflict between x64 and x86

**Comment by jlk1997** [comment]
its my entire output after the 3 commands
  gl3w.c
gl3w.obj : error LNK2019: 无法解析的外部符号 __imp_wglGetProcAddress，函数 gl3wGetProcAddress 中引用了该符号 [E:\GLSL-PathTracer-master\bu
ild\PathTracer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64\opengl32.lib : warning LNK427
2: 库计算机类型“x86”与目标计算机类型“x64”冲突 [E:\GLSL-PathTracer-master\build\PathTracer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64\glu32.lib : warning LNK4272:
库计算机类型“x86”与目标计算机类型“x64”冲突 [E:\GLSL-PathTracer-master\build\PathTracer.vcxproj]
E:\GLSL-PathTracer-master\build\PathTracer.exe : fatal error LNK1120: 1 个无法解析的外部命令 [E:\GLSL-PathTracer-master\build\PathTracer.vcxproj]
![image](https://user-images.githubusercontent.com/56379549/211452658-310594c1-56a9-4865-836c-6d2b66102ecb.png)

**Comment by knightcrawler25** [comment]
My VS 2022 gets the opengl32.lib and glu32.lib from the Windows SDK lib folder
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64`  (SDK version might be different from what you have installed)

I'm not sure how, but the opengl32.lib and glu32.lib that you have in the following folders seem to be 32 bit versions of the library and not 64 bit. Try taking a backup and removing them from the folder, try building again and see if VS is still able link correctly
```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64\opengl32.lib
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64\glu32.lib
```

If linking fails, try re-installing windows SDK (https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/)

**Comment by jlk1997** [comment]
ohhhhhhh！！！！！！why？？！！！After delete opengl32. Lib and Glu32. Lib, the program runs successfully! But I removed  these two static libraries under vs, the project is where to find the relative static library??
By the way,its a cool coool coooool project,I will be very serious to study this set of engineering, thank you！！！！！！

**Comment by knightcrawler25** [comment]
After deleting the .lib files, your VS probably picks another one from the default Windows SDK path. Anyway, glad to hear that the issue is fixed now :)
