### ISSUE TITLE
HI!!!u are so awsome that could write so large programme. im a student,and i want to know how to learn it ? or do sir have some course about it?

### ISSUE THREAD

**Issue by jlk1997** [knightcrawler25/GLSL-PathTracer#81]
thx

**Comment by knightcrawler25** [comment]
Thanks!

You'll find a lot of resources on this page https://www.realtimerendering.com/raytracing.html

If you're just starting out, then then the "Ray Tracing in One Weekend" series by Peter Shirley (https://raytracing.github.io/) is a great way to learn as it teaches you how to build a path tracer from scratch.

Once you've covered the fundamentals, https://www.pbr-book.org/ will teach you everything else that you ought to know. Many production renderers like RenderMan, Cycles etc. are built on the same principles.

Hope this helps :)
