### ISSUE TITLE
How to export Blender scene step by step?

### ISSUE THREAD

**Issue by odil24** [knightcrawler25/GLSL-PathTracer#82]
Hi. Is there have any solution?

**Comment by knightcrawler25** [comment]
I don't have a plugin for Blender but you can use the python script I've added in this blend file [export.zip](https://github.com/knightcrawler25/GLSL-PathTracer/files/10889606/export.zip) to export simple scenes as a .scene file that my renderer can read

Load up the .blend file and run the script

![image](https://user-images.githubusercontent.com/11459803/222927238-7162a2dc-a3c1-4535-bd42-a4854a60380a.png)

Copy the exported meshes folder and the export.scene file from the blend file's directory to the renderer's assets folder and it should work. Note: Only basic scenes will work. Material graphs, textures etc. will not work unless you modify the python script into a full fledged exporter.

![image](https://user-images.githubusercontent.com/11459803/222927096-81b73d37-433f-44fe-b19f-29b5f028a99b.png)

**Comment by odil24** [comment]
> I don't have a plugin for Blender but you can use the python script I've added in this blend file [export.zip](https://github.com/knightcrawler25/GLSL-PathTracer/files/10889606/export.zip) to export simple scenes as a .scene file that my renderer can read
> 
> Load up the .blend file and run the script
> 
> ![image](https://user-images.githubusercontent.com/11459803/222927238-7162a2dc-a3c1-4535-bd42-a4854a60380a.png)
> 
> Copy the exported meshes folder and the export.scene file from the blend file's directory to the renderer's assets folder and it should work. Note: Only basic scenes will work. Material graphs, textures etc. will not work unless you modify the python script into a full fledged exporter.
> 
> ![image](https://user-images.githubusercontent.com/11459803/222927096-81b73d37-433f-44fe-b19f-29b5f028a99b.png)

Hi. Thanks for reply. I have not also your latest version which you used now. And also i just export as you said but camera is not exported as in Blender. Can you upload latest version of GLSLPT?

**Comment by knightcrawler25** [comment]
The camera model in the repo is simple doesn't support tilting, so if the camera in your scene has a rotation on the Y axis then it won't get exported the same way as Blender.

I've added the latest version to the repo: https://github.com/knightcrawler25/GLSL-PathTracer/releases/tag/v0.5.0
