### ISSUE TITLE
why use tile rendering

### ISSUE THREAD

**Issue by qstx** [knightcrawler25/GLSL-PathTracer#84]
Hi, I have to admit it's a pretty cool project，but I have a question about the tile rendering. Why would you think of rendering a small tile multiple times, which seems to be indistinguishable from rendering the entire frame at once?

**Comment by knightcrawler25** [comment]
Hey :) Rendering the frame a tile at a time increases responsiveness of the application on older GPUs.

Some background:

The project is aimed at older GPUs that do not have support for hardware-accelerated RT. That is why everything from BVH traversal, and ray-triangle intersections to shading is done in a pixel shader. This allows people with old yet relatively decent GPUs to run the code. However, pixel shaders have their limitations as there's no control over how work gets executed on the GPU. This, along with the compute intensive nature of path tracing would mean rendering the entire frame at once will often cause the GPU to hang up and the display driver to crash. A simple solution to this is to split the rendering into small tiles, essentially simulating what CUDA/Computer shaders explicitly allow you to do (in an very unsophisticated way of course).

With Vulkan/DXR/OptiX, significantly higher performance can be achieved with the cost of being locked to a vendor and/or the need to have a modern GPU that supports hardware-accelerated RT.

**Comment by qstx** [comment]
Thanks a lot for your quick answer, it lets me know why you're doing this. ≧◠◡◠≦

**Comment by qstx** [comment]
Hey :) I just make a simple real-time raytracing (with gpu filtering) using your framework. Can I make this repositorie public? Here is my url(https://github.com/qstx/Real-Time-GLSL-Based-PathTracing).

**Comment by ib00** [comment]
You mention that pixel shaders are executed in a different way than compute shaders
(hence need of tiles). Is there a good reference describing this (difference of pixel vs
compute shaders are executed)?

Thanks.

**Comment by ib00** [comment]
Thanks for the link. Good explanation.
