### ISSUE TITLE
when rendering，why divide a Framebuffer into some Tiles

### ISSUE THREAD

**Issue by wilking131** [knightcrawler25/GLSL-PathTracer#86]
i cant understand，will more faster？why？I think it increases the consumption  of framebuffer switching.

**Comment by wilking131** [comment]
thank you a lot

**Comment by wilking131** [comment]
When I switched from using tiles to a single Framebuffer and deleted them, the frame rate improved threefold in multiple scenes. I can't believe there was such a significant improvement.

**Comment by knightcrawler25** [comment]
The perf improvement comes at the cost of responsiveness. On heavier scenes, you would start seeing menus, mouse movements lag as the GPU is busy rendering the frame.

Also, you can try modifying the tilewidth and tileheight in the scene file as it should allow for a similar performance improvement.
