### ISSUE TITLE
Absorption

### ISSUE THREAD

**Issue by markusmoenig** [knightcrawler25/GLSL-PathTracer#89]
Hi,

this BSDF Light shader has an easy to use absorption parameter for liquids: https://www.shadertoy.com/view/Dtl3WS.

How can I recreate an absorption parameter like this using GLSL-PathTracer ?

Thanks

**Comment by knightcrawler25** [comment]
Hey,

You'll first need to make the material transmissive (specTrans = 1.0) and then set Medium Type = Absorb
Then you can tweak the absorption color using Medium Color and the Medium Density params

![image](https://github.com/knightcrawler25/GLSL-PathTracer/assets/11459803/d9ada2c5-4647-4150-8ad0-fbde8059f4b0)

**Comment by markusmoenig** [comment]
Thanks!
