### ISSUE TITLE
Water in tropical island scene is always black

### ISSUE THREAD

**Issue by AllSeeingEye** [knightcrawler25/GLSL-PathTracer#94]
No matter the options, water in tropical island scene is always black for me
(NVidia GTX 1060, latest drivers).

What setting(s) should I use for the scene to look like a screenshot you have?
Or should I just wait for enough samples?

![Tropical_Island](https://github.com/knightcrawler25/GLSL-PathTracer/assets/469746/02e84622-d65b-42ec-9c57-26dd470e1d8b)

**Comment by knightcrawler25** [comment]
Perhaps you have the "Max Depth" set to a low value and have disabled "Volume MIS"?

Here's how the default settings look like:
![image](https://github.com/knightcrawler25/GLSL-PathTracer/assets/11459803/906625af-5fe8-4e09-8aae-de94c368c25f)

**Comment by AllSeeingEye** [comment]
Screenshot with exactly that settings:

![img_10](https://github.com/knightcrawler25/GLSL-PathTracer/assets/469746/ced3a02e-7d4f-4e8b-b771-fe9eacd728b9)

**Comment by knightcrawler25** [comment]
You might be missing the HDR file for the scene. Try copying all the HDRs from assets.rar

**Comment by AllSeeingEye** [comment]
Yes, that was the issue. Thank you! And sorry for confusion.
