### ISSUE TITLE
Is it possible make Blender addon not exporter?

### ISSUE THREAD

**Issue by odil24** [knightcrawler25/GLSL-PathTracer#95]
@knightcrawler25 I mean can we make it as LuxCoreRender addon for Blender not an exporter?

**Comment by knightcrawler25** [comment]
I don't see a point in turning this into an addon for Blender. Cycles, a production renderer, already exists for it and has far more features that what this project offers. There are other options like LuxCore as well.

This project is mainly meant for people who are trying to learn how path tracing works. It's not meant to be a production renderer or a full fledged DCC.
